### ISSUE TITLE
The app does not restore menu's colors after closed

### ISSUE THREAD

**Issue by vic4key** [krlvm/AcrylicMenus#10]
I run the app, it works (only desktop's context menu). After the app closed, the menu's colors does not restore back the original. I already tried to switch between themes, but it is not resolved. Even I rebooted PC. Please help me with a workaround or an update ASAP. Thanks.

![2](https://user-images.githubusercontent.com/5672864/172815425-7bcecd35-15c2-48f3-89fb-c0e1628db657.PNG)

![1](https://user-images.githubusercontent.com/5672864/172815436-043ccc22-0d28-44f2-992d-b3676416b42e.PNG)
.

**Comment by krlvm** [comment]
This app is not stable yet, and I'm still looking for other ways to implement this without changing the system colors
You can enable and disable high contrast theme to restore correct colors

**Comment by vic4key** [comment]
Your workaround works. Resolved this issue. Thanks.
