### ISSUE TITLE
Additional option to change Contextmenu color

### ISSUE THREAD

**Issue by Kratos-Mundus** [krlvm/AcrylicMenus#11]
Could you add a feature that give´s the option to modify the RGB color of the Contextmenu ?

**Comment by krlvm** [comment]
The current version of AcrylicMenus has fundamental flaws, so I don't think I will be making any changes to it.

In the meantime, I have quite a lot of success in modifying and improving [TranslucentFlyouts](https://github.com/ALTaleX531/TranslucentFlyouts) at the cost of removing some functionality, customizability and limiting the scope of the program to only the File Explorer, so I will be able to submit the pull request if @ALTaleX531 won't mind it.

https://user-images.githubusercontent.com/51774833/181856716-c68030c2-04a4-4aa3-87a6-7b1e599a392c.mp4

https://user-images.githubusercontent.com/51774833/181855640-68122e9b-736e-45e6-ac68-67adcae2a368.mp4

**Comment by Kratos-Mundus** [comment]
So, if I understand it right, for new improvements or features I should go to this Project https://github.com/ALTaleX531/TranslucentFlyouts and ask for it ?
And what about this Project will it be dead and the new Project for acrylic effects is that one from ALTaleX531 ?

**Comment by krlvm** [comment]
I have significantly improved and fixed some issues in TranslucentFlyouts and will be able to submit the changes soon, however, if the author has a different vision, I will update AcrylicMenus based on the TranslucentFlyouts codebase, I think i will finish it in the next few days.
