### ISSUE TITLE
Visual glitch in hardware removal menu in system tray when using dark theme.

### ISSUE THREAD

**Issue by rangan2510** [krlvm/AcrylicMenus#12]
![image](https://user-images.githubusercontent.com/32454244/188099914-6a953f53-87a1-4185-bea6-2a8779173e48.png)

Refer to the attached image for further details.

**Comment by Dhyfer1** [comment]
There is also the bug when I want to add a new column in the file explorer. I hope the new version can fix it
![2022-09-09_21-29-53](https://user-images.githubusercontent.com/50301201/189465527-1e06e047-5f88-48d9-bcf0-3e2241315dbb.png)

**Comment by krlvm** [comment]
Fixed in [version 1.0.1](https://github.com/krlvm/AcrylicMenus/releases/tag/v1.0.1).

**Comment by Dhyfer1** [comment]
Thanks, this new version does fix the bug mentioned in this issue.

Just a small detail, although the dll file indicates the new version, this version is not shown when using the install.cmd file. I just wanted to let you know, otherwise this new version works without problem.

![image_12](https://user-images.githubusercontent.com/50301201/189541817-22113faf-e6a3-4d61-b95c-8c6e3e3eeada.png)

**Comment by krlvm** [comment]
I think I was too lazy to edit it.

I'll release version 2.0 soon, which is not based on TranslucentFlyouts and allows to apply the acrylic effect to menus that does not belong to Explorer windows.

**Comment by Dhyfer1** [comment]
Great! I look forward to that new version soon. What you say sounds very interesting to see

**Comment by Dhyfer1** [comment]
> I'll release version 2.0 soon, which is not based on TranslucentFlyouts and allows to apply the acrylic effect to menus that does not belong to Explorer windows.

Hey @krlvm Is there any progress on this? The last AcrylicMenus update was a little over two months ago, while TranslucentFlyouts was updated 3 weeks ago. I would just like to see if the update you mention could work with Qttabbar menus using the file explorer in dark mode.

![image_2](https://user-images.githubusercontent.com/50301201/210453848-abe8c85a-040f-462c-9505-7bb20abc90c3.png)

**Comment by krlvm** [comment]
I had to drop the idea of hooking the TrackPopupMenuEx as it causes even more compatibility issues, don't have any news for now

**Comment by Dhyfer1** [comment]
Oh, that's fine. I hope AcrylicMenus continues to be updated.
