### ISSUE TITLE
Missing selection highlight/outline for arrow key navigation

### ISSUE THREAD

**Issue by Expertcoderz** [krlvm/AcrylicMenus#14]
While navigating/selecting items in a context menu using the up/down arrow keys, there is no indication of the currently selected item by means of a highlight or outline around that item (as Windows has by default).

#### Without AcrylicMenus (note the expected outline around the selected item, "Sort by"):

![image](https://user-images.githubusercontent.com/81153405/193509334-2df42787-20b4-4edb-8d2c-3f088a84143c.png)

#### With AcrylicMenus:

![image](https://user-images.githubusercontent.com/81153405/193508672-db7ec6fe-a9b3-4c5d-a403-1ecbb43abbc9.png)

The items are of course still usable by activation, just that the selection would be blind.

(This is the same for context menus in File Explorer.)

I am on Windows 11 Pro, Version 22H2, Build 22622.598.

**Comment by ilovepcs** [comment]
This is the newly added part 26 in the Menu class in msstyles. I hope krlvm sees this.

**Comment by krlvm** [comment]
I'm already working on the fix along with rounding highlight boxes (#13).
This is already fixed in TranslucentFlyouts though.

**Comment by krlvm** [comment]
Fixed in [version 1.0.3](https://github.com/krlvm/AcrylicMenus/releases/tag/v1.0.3)
