### ISSUE TITLE
Still no Acrylic for Windows 10 

### ISSUE THREAD

**Issue by HuyHung1408** [krlvm/AcrylicMenus#2]
![image](https://user-images.githubusercontent.com/86362423/145699834-3fe09d13-dffd-40da-9574-7fa06b3bc04d.png)

**Comment by krlvm** [comment]
This is an experimental app and does not always work correctly, it should show acrylic on, at least, File Explorer context menus on 19H1 and higher. Do you use a custom msstyles theme?

**Comment by HuyHung1408** [comment]
I'm not using any themes and system drive is C:/ drive

**Comment by krlvm** [comment]
No, it can't be related. Since there's a Windows 11 version, are you sure you've used AcrylicMenus-Windows10.zip?
How does your File Explorer context menu look like? It should have background color `RGB(238, 238, 238)` or `RGB(43, 43, 43)` if you use dark theme.

**Comment by HuyHung1408** [comment]
https://user-images.githubusercontent.com/86362423/145711050-8480d6e1-d907-4914-9bd8-8c6798124abe.mp4

**Comment by krlvm** [comment]
I deeply apologize if I did not mention this separately, but closing the window or pressing any key results in unhooking and unloading the program from memory. You should open context menus when the console window is opened.
I have not added a quiet mode, as the program is currently in an early state of development and the quality of its work may disappoint you.

**Comment by HuyHung1408** [comment]
oh, thank you a lot. Works now. It's not disappointed me because, for me, this is great work since nobody else has done this before although it's still in development. Nice work, keep going!
