### ISSUE TITLE
Not functioning on arm64

### ISSUE THREAD

**Issue by SWEATSHOPKING** [krlvm/AcrylicMenus#24]
not sure if this is obvious or by design, but i'm not getting any functionality on windows 11 arm64 - surface pro x. Is there anything i can try or do to make it work?

**Comment by krlvm** [comment]
You need to build ARM64 binary

**Comment by SWEATSHOPKING** [comment]
Thanks! i have no idea how to do that, so i'll just have to wait for a smarter person with the same concern! thanks for the update and clarification!
