### ISSUE TITLE
How do I uninstall AcrylicMenus?

### ISSUE THREAD

**Issue by mativerval** [krlvm/AcrylicMenus#26]
Hello, I am trying to uninstall AcrylicMenus so I can use TranslucentFlyouts. I installed AcrylicMenus about a year ago and I'm not sure where I extracted the release. Is there any simple way to disable or uninstall AcrylicMenus?

**Comment by krlvm** [comment]
There's an Uninstaller in the archive, but if you want to uninstall it manually:
- Kill `AcrylicMenusLoader.exe` process
- If you installed it for local user only:
- - Delete `%LocalAppData%\AcrylicMenus`
- - Remove autorun entry from `HKCU\Software\Microsoft\Windows\CurrentVersion\Run`
- If you installed it for all users:
- - Delete `%ProgramFiles%\AcrylicMenus`
- - Remove autorun entry from `HKLM\Software\Microsoft\Windows\CurrentVersion\Run`

**Comment by trojankeygen32** [comment]
Hi, sorry for the late response. Even though it looks like I still have AcrylicMenus installed, I looked at all the folders and registry entries you listed and there was nothing to be found. I installed the 0.5 version last year and am wondering if it is coming from that. Do you know of any way to uninstall the 0.5 version? Here is a screenshot of what my context menu looks like:
![Screenshot (3)](https://github.com/krlvm/AcrylicMenus/assets/141959751/0506846c-036b-4c7d-aeaf-0f96b25cac29)
