### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by PIndividual** [krlvm/AcrylicMenus#4]
![image](https://user-images.githubusercontent.com/62368342/147807326-a87ba399-b016-4366-940a-357ebff1033e.png)

**Comment by krlvm** [comment]
Are you using a custom theme?

**Comment by PIndividual** [comment]
I did replace my windows aero theme file with the one on earlier builds of Windows 11, does that causes this?

**Comment by HuyHung1408** [comment]
> I did replace my windows aero theme file with the one on earlier builds of Windows 11, does that causes this?

It had some elements like Windows 11 checkbox, right?

**Comment by krlvm** [comment]
> I did replace my windows aero theme file with the one on earlier builds of Windows 11, does that causes this?

Yes, you should use the build for Windows 11. The difference in the two builds just in colors.

**Comment by PIndividual** [comment]
> > I did replace my windows aero theme file with the one on earlier builds of Windows 11, does that causes this?
> 
> It had some elements like Windows 11 checkbox, right? ![image](https://user-images.githubusercontent.com/86362423/147842310-b59eb596-047a-44a0-afff-795d5ffb8641.png)

Yes, now my checkboxes are in Windows 11's style

**Comment by PIndividual** [comment]
> > I did replace my windows aero theme file with the one on earlier builds of Windows 11, does that causes this?
> 
> Yes, you should use the build for Windows 11. The difference in the two builds just in colors.

Okay, I'll try.

**Comment by PIndividual** [comment]
It works! But it seems to be performance issue since the context menu always get stuck and the secondary context is not working :(
![image](https://user-images.githubusercontent.com/62368342/147853027-5377ba3c-e632-446b-be2f-a2486ebd4548.png)

**Comment by HuyHung1408** [comment]
![image](https://user-images.githubusercontent.com/86362423/147853081-266f41e8-432f-4332-87b0-4f6547c10029.png)
it's working for me

**Comment by krlvm** [comment]
Unfortunately it has some limitations because the acrylic effect can't be applied instantly and is being applied via undocumented API call.
I have an idea on how to fix font rendering and delay before effect is applied, but this would be limited to File Explorer only.

**Comment by krlvm** [comment]
https://github.com/krlvm/AcrylicMenus/issues/1#issuecomment-1004235481
