### ISSUE TITLE
Error was unable to start correclty

### ISSUE THREAD

**Issue by lazycodebaker** [krlvm/AcrylicMenus#5]

**Comment by krlvm** [comment]
Details?

**Comment by lazycodebaker** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/87172624/151687115-ad151a21-aace-4540-baec-7a07cafd951b.png)

Error while running the injector file

**Comment by lazycodebaker** [comment]
> Details?

Given the image above 👆

**Comment by krlvm** [comment]
I think it's because you're running an Insider build - i tested it only on stable builds.

**Comment by lazycodebaker** [comment]
> I think it's because you're running an Insider build - i tested it only on stable builds.

I also tested it on stable build 22000.3__

**Comment by krlvm** [comment]
You need to install Microsoft Visual C++ Redistributable package
https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by lazycodebaker** [comment]
> You need to install Microsoft Visual C++ Redistributable package https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170

checking ...
